############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2


[[main]]
weight = 3
name = "Blog"
url = "/blog"

[[main]]
weight = 4
name = "Services"
url = "/services"

[[main]]
weight = 5
name = "Methodology"
url = "/methodology"


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Services"
url = "/services"
weight = 2

[[footer]]
name = "Contact"
url = "/contact"
weight = 3
