############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
weight = 3
name = "Blog"
url = "/blog"

[[main]]
weight = 4
name = "Services"
url = "/services"

[[main]]
weight = 1
parent = "Services"
name = "Data Strategy"
url = "/services/strategy"

[[main]]
weight = 2
parent = "Services"
name = "Data Science"
url = "/services/analytics"

[[main]]
weight = 3
parent = "Services"
name = "Data Engineering"
url = "/services/engineering"

[[main]]
weight = 4
parent = "Services"
name = "Data Governance"
url = "/services/governance"

[[main]]
weight = 5
parent = "Services"
name = "Data Integration"
url = "/services/integration"

[[main]]
weight = 6
parent = "Services"
name = "Data Archeology"
url = "/services/archeology"

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Contact"
url = "/contact"
weight = 2
